---
title: "Untitled"
author: "Peter Kariuki"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse")
library(tidyverse) # A family of packages used to clean, process, model, and visualize data

# install.packages("sf")
library(sf) # Offers Support for simple features, a standardized way to encode spatial vector data. Binds to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and to 'PROJ' for projection conversions and datum transformations.

# install.packages("devtools")
# devtools::install_github("Shelmith-Kariuki/rKenyaCensus")
library(rKenyaCensus) # Contains the 2019 Kenya Census data

# install.packages("ggplot2") 
library(ggplot2) # Used for creating amazing pretty graphs in R

# install.packages("tmap") #Thematic maps are geographical maps in which spatial data distributions are visualized
library(tmap)

# install.packages("leaflet") # Used for creating interactive maps
library(leaflet)
```

```{r}
KenyaSHP <- read_sf("C:/Users/HP/Downloads/mwi_adm_nso_20181016_shp (2)", quiet = TRUE, stringsAsFactors = FALSE,as_tibble = TRUE)
View(KenyaSHP %>% st_drop_geometry())
class(KenyaSHP)
```

```{r}
### This line is not necessary since the shapefile is already in the WGS 84 projection.

KenyaSHP <- st_transform(KenyaSHP, crs = 4326)

### Inspect the co-ordinate reference system
st_crs(KenyaSHP)
```

```{r}
data <- read_csv("C:/Users/HP/Downloads/dryspell.csv")
### Merge the data
merged_df <- left_join(KenyaSHP, data, by = "ADM2_PCODE")

### Sort the data so that the County variable appears first
merged_df <- merged_df %>% 
  select(ADM2_PCODE, everything())
class(merged_df)
```

```{r}
plot(KenyaSHP$geometry, lty = 3, col = "darkgreen")
```

```{r}
map1 <- ggplot(data = merged_df)+
          geom_sf(aes(geometry = geometry, fill = Counter))+ geom_sf_label(aes(label = ADM2_EN))
            theme_void()+
            labs(title = "Distribution of Population with Vision Disability",
                 caption = "By: Peter")+
            theme(plot.title = element_text(family = "URW Palladio L, Italic",size = 16, hjust = 0.5),
                  legend.title = element_blank(),
                  plot.caption = element_text(family = "URW Palladio L, Italic",size = 12))+
  #scale_fill_gradient(low = "darkgreen", high = "red")
  scale_fill_viridis_c()
           
map1



nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
  geom_sf(aes(fill = AREA))

nc_3857 <- sf::st_transform(nc, 3857)
ggplot() +
  geom_sf(data = nc) +
  geom_sf(data = nc_3857, colour = "red", fill = NA)


ggplot(nc_3857[1:3, ]) +
   geom_sf(aes(fill = AREA)) +
   geom_sf_label(aes(label = NAME))
```

```{r}
tmap_mode("plot") #Set tmap mode to static plotting or interactive viewing

map2 <- tm_shape(merged_df) +
  tm_fill("Counter",palette="Greens",
          title="Distribution of Population with Vision Disability", 
          id = "ADM2_PCODE") +
  tm_borders(col = "red",lty = 3)+
  tm_layout(legend.position = c("left", "bottom"))
map2
```


```{r}
### Specify the color scheme
pal <- colorBin(
  palette = "YlOrRd",
  domain = merged_df$Counter
)
library(htmltools)
merged_df$hover = with(merged_df, paste(ADM2_EN, '<br>', "Number of Dryspells:", Counter))
labs <- as.list(merged_df$hover)
labels = lapply(labs,HTML)


### Specify how labels will be displayed
# labels <- sprintf(
#   "<strong>%s</strong><br/>%s Number of Dryspells",
#   merged_df$ADM2_EN, merged_df$Counter
# ) %>% lapply(htmltools::HTML)

### Generate the graph
leaflet(merged_df) %>%
  setView(33.78725,-13.96692,zoom=7) %>%
  addTiles() %>% 
  addPolygons(color = "red", weight = 1, dashArray = "3", fillColor = ~pal(Counter),
              highlight = highlightOptions(
                weight = 4,
                color = "red",
                dashArray = "",
                bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addLegend(position = c("bottomright"),pal = pal, values = ~Counter)
```

