---
title: "Untitled"
author: "Peter Kariuki"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, comment = FALSE,warning = F)
```

```{r}
#install.packages("tidyverse")
library(tidyverse) # A family of packages used to clean, process, model, and visualize data

# install.packages("sf")
library(sf) # Offers Support for simple features, a standardized way to encode spatial vector data. Binds to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and to 'PROJ' for projection conversions and datum transformations.

# install.packages("devtools")
# devtools::install_github("Shelmith-Kariuki/rKenyaCensus")
library(rKenyaCensus) # Contains the 2019 Kenya Census data

# install.packages("ggplot2") 
library(ggplot2) # Used for creating amazing pretty graphs in R

# install.packages("tmap") #Thematic maps are geographical maps in which spatial data distributions are visualized
library(tmap)

# install.packages("leaflet") # Used for creating interactive maps
library(leaflet)
```

```{r}
KenyaSHP <- read_sf("C:/Users/HP/Downloads/kenyan-counties", quiet = TRUE, stringsAsFactors = FALSE,as_tibble = TRUE)
#View(KenyaSHP %>% st_drop_geometry())
#class(KenyaSHP)
```

```{r}
### This line is not necessary since the shapefile is already in the WGS 84 projection.

KenyaSHP <- st_transform(KenyaSHP, crs = 4326)

### Inspect the co-ordinate reference system
#st_crs(KenyaSHP)
```

```{r}
Disability_df <- V4_T2.27

# clean County names
### Inspect the county names of the disability data
counties_Disability_df <- unique(Disability_df$County)

### Inspect the county names of the shape file
counties_KenyaSHP <- KenyaSHP %>% 
  st_drop_geometry() %>% 
  select(COUNTY) %>% 
  pull() %>%
  unique()

### Convert the disability county names to title case
Disability_df <- Disability_df %>% 
  ungroup() %>% 
  mutate(County = tools::toTitleCase(tolower(County)))

### Inspect the county names of the disability data again 
counties_Disability_df <- unique(Disability_df$County)

### Inspect the county names that are different in each of the datasets
unique(Disability_df$County)[which(!unique(Disability_df$County) %in% counties_KenyaSHP)]
#> [1] "Xxx"             "Taita/Taveta"    "Tharaka-Nithi"   "Elgeyo/Marakwet"
#> [5] "Nairobi City"

### Clean the county names so that they match in both datasets
Disability_df <- Disability_df %>% 
  mutate(County = ifelse(County == "Taita/Taveta", "Taita Taveta",
                  ifelse(County == "Tharaka-Nithi", "Tharaka",
                  ifelse(County == "Elgeyo/Marakwet", "Keiyo-Marakwet",
                  ifelse(County == "Nairobi City", "Nairobi", County)))))


### Inspect the county names again to ensure that they now match.
unique(Disability_df$County)[which(!unique(Disability_df$County) %in% counties_KenyaSHP)]


Disability_df2 <- Disability_df %>% 
  filter(AdminArea == "County") %>% 
  select(-AdminArea, -SubCounty)
```

```{r}
### Rename the COUNTY variable, to match the variable name in the shapefile data
Disability_df2 <- Disability_df2 %>% 
  rename(COUNTY = County)

### Ensure that there are no leading or trailing spaces in the county variable
KenyaSHP$COUNTY <- trimws(KenyaSHP$COUNTY)
Disability_df2$COUNTY <- trimws(Disability_df2$COUNTY)

### Merge the data
merged_df <- left_join(KenyaSHP, Disability_df2, by = "COUNTY")

### Sort the data so that the County variable appears first
merged_df <- merged_df %>% 
  select(COUNTY, everything())
#class(merged_df)
```


```{r}
map1 <- ggplot(data = merged_df)+
          geom_sf(aes(geometry = geometry, fill = Vision_Total))+
            theme_void()+
            labs(title = "Distribution of Population with Vision Disability",
                 caption = "Caption Here")+
            theme(plot.title = element_text(family = "URW Palladio L, Italic",size = 16, hjust = 0.5),
                  plot.caption = element_text(family = "URW Palladio L, Italic",size = 12))+
  #scale_fill_gradient(low = "darkgreen", high = "red")
  scale_fill_viridis_c()
           
map1
```

```{r}
tmap_mode("plot") #Set tmap mode to static plotting or interactive viewing

map2 <- tm_shape(merged_df) +
  tm_fill("Vision_Total",palette="Greens",
          title="Population", 
          id = "COUNTY") +
  tm_borders(col = "black",lty = 1)+
  tm_layout(legend.outside.position = c("left", "bottom"),main.title = "Population with Vision Disability",main.title.position = "center")
map2
```

```{r}
current.mode <- tmap_mode("plot")

data(World, metro, rivers)
tm_shape(World, projection="+proj=eck4") +
    tm_fill("darkolivegreen3") +
tm_shape(metro) +
    tm_bubbles("pop2010", col = "grey30", scale=.5) +
tm_shape(rivers) +
    tm_lines("lightcyan1") +
tm_layout(bg.color="lightcyan1", inner.margins=c(0,0,.02,0), legend.show = FALSE)+
  tm_layout("Long lat coordinates (WGS84)", inner.margins=c(0,0,.1,0), title.size=.8)

```


```{r}
### Specify the color scheme
pal <- colorBin(
  palette = "YlOrRd",
  domain = merged_df$Vision_Total
)

### Specify how labels will be displayed
labels <- sprintf(
  "<strong>%s</strong><br/>%g",
  merged_df$COUNTY, merged_df$Vision_Total
) %>% lapply(htmltools::HTML)

### Generate the graph
leaflet(merged_df) %>%
  addTiles() %>% 
  addPolygons(color = "red", weight = 1, dashArray = "3", fillColor = ~pal(Vision_Total),
              highlight = highlightOptions(
                weight = 4,
                color = "red",
                dashArray = "",
                bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>% 
  addLegend(position = c("bottomright"),pal = pal, values = ~Vision_Total)
```

